In [1]:
import numpy as np

## 기본적인 벡터나 행렬을 선언하는 방법

In [2]:
temp = [1,2,3,4,5]
vector = np.array(temp)
vector

array([1, 2, 3, 4, 5])

In [3]:
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [5]:
matrix = np.array([[1,2,3,],
                  [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [6]:
# 타입
print(type(matrix))

<class 'numpy.ndarray'>


### 벡터화 연산

In [7]:
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [8]:
print(vector*2)

[ 2  4  6  8 10]


In [9]:
print(vector>1)

[False  True  True  True  True]


### 인덱싱(인덱스 번호로 접근) , 슬라이싱

In [10]:
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [11]:
print(vector[1])

2


In [13]:
print(vector[2:4])

[3 4]


### 차원과 크기

In [14]:
#차원
matrix = np.array([[1,2,3,],
                  [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [15]:
# 변수이름.ndim
print(matrix.ndim)

2


In [17]:
a = np.array(1)
print(a.ndim)

0


배열의 차원 및 크기를 구하는 더 간단한 방법은 배열의 ndim 속성과 shape 속성을 이용하는 것이다. ndim 속성은 배열의 차원, shape 속성은 배열의 크기를 반환한다.

In [18]:
#배열의 크기
print(matrix.shape)

(2, 3)


In [25]:
# 배열 안의 원소의 갯수를 세려면?
#배열의 크기 사용하기
print(len(matrix))
print(matrix.size)

temp=1
for i in matrix.shape:
    temp *=i
print(temp)

2
6
6


## 기본 행렬끼리 곱하기(행렬곱)

In [26]:
#np.dot
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [27]:
# A의 역행렬
A_inv = np.linalg.inv(A)

In [28]:
#행렬과 행렬의 곱의 결과는 항등행렬이다.
np.dot(A,A_inv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [31]:
#A와 똑같은 크기의 항등행렬
np.eye(A.ndim)

array([[1., 0.],
       [0., 1.]])

In [32]:
temp = np.array([[2],[1]])
print(temp)

[[2]
 [1]]


In [33]:
np.dot(A_inv,temp)

array([[-3. ],
       [ 2.5]])